version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - my-network

  backend:
    build: ./backend
    ports:
      - 8002:8002
    networks:
      - my-network

networks:
  my-network: